import { createEntityStore } from './entityStore';
import { adminUserStore } from './adminUsers';
import { auditStore } from './auditService';

export const couponStore = createEntityStore('coupons_v2', [], { persist: false });
export const promotionStore = createEntityStore('promotions_v2', [], { persist: false });
export const orderStore = createEntityStore('orders_v9', [], { persist: false });
export const riderStore = createEntityStore('riders_v9', [], { persist: false });
export const customerStore = createEntityStore('customers_v9', [], { persist: false });
export const ticketStore = createEntityStore('tickets_v2', [], { persist: false });
export const paymentStore = createEntityStore('payments_v9', [], { persist: false });
export const vehicleStore = createEntityStore('vehicles_v2', [], { persist: false });
export const zoneStore = createEntityStore('zones_v2', [], { persist: false });
export const invoiceStore = createEntityStore('invoices_v2', [], { persist: false });
export const purchaseInvoiceStore = createEntityStore('purchase_invoices_v2', [], { persist: false });
export const walletStore = createEntityStore('wallet_v9', [], { persist: false });
export const announcementStore = createEntityStore('announcements_v2', [], { persist: false });
export const campaignStore = createEntityStore('campaigns_v9', [], { persist: false });
export const payoutStore = createEntityStore('payouts_v3', [], { persist: false });
export { adminUserStore, auditStore };
