import { Workbook } from 'exceljs';
import { GstDetailRow, GstGroupRow, GstSummaryRow } from './gst-report.repository';
import { ResolvedRange } from './date-range';

/**
 * Two-sheet GST workbook, generated in the backend so the file always matches
 * the same SQL aggregation the screen shows.
 *
 * Deliberately excluded: passwords, OTPs, tokens, bank details, documents and
 * document URLs. Only the customer name and rider phone already exposed to
 * finance admins are included.
 */

const MONEY_FORMAT = '#,##0.00';

export type WorkbookInput = {
  range: ResolvedRange;
  generatedAt: Date;
  generatedBy: string;
  appliedFilters: Record<string, string>;
  summary: GstSummaryRow;
  groups: GstGroupRow[];
  groupLabel: string;
  detail: GstDetailRow[];
  truncated: boolean;
  exportMaxRows: number;
};

function money(value: string | null): number | null {
  if (value == null) return null;
  return Number(value);
}

export async function buildGstWorkbook(input: WorkbookInput): Promise<Buffer> {
  const workbook = new Workbook();
  workbook.creator = 'IDHAR UDHAR Admin';
  workbook.created = input.generatedAt;

  buildSummarySheet(workbook, input);
  buildTransactionsSheet(workbook, input);

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

function buildSummarySheet(workbook: Workbook, input: WorkbookInput): void {
  const sheet = workbook.addWorksheet('Summary');
  sheet.columns = [
    { width: 38 },
    { width: 22 },
    { width: 16 },
    { width: 18 },
    { width: 18 },
    { width: 18 },
    { width: 18 },
    { width: 18 },
    { width: 18 },
  ];

  const title = sheet.addRow(['IDHAR UDHAR — GST & Financial Report']);
  title.font = { bold: true, size: 14 };
  sheet.addRow([
    'Scope: trip commission GST. GST on the customer trip fare is 0 and is not part of this report.',
  ]);
  sheet.addRow([]);

  addLabelled(sheet, 'Report period', `${input.range.from_date} to ${input.range.to_date}`);
  addLabelled(sheet, 'Date preset', input.range.preset);
  addLabelled(sheet, 'Date basis', 'Finance freeze date (order_finance_snapshots.frozen_at)');
  addLabelled(sheet, 'Time zone', input.range.time_zone);
  addLabelled(sheet, 'Generated at', input.generatedAt.toISOString());
  addLabelled(sheet, 'Generated by', input.generatedBy);
  sheet.addRow([]);

  const filtersHeader = sheet.addRow(['Applied filters']);
  filtersHeader.font = { bold: true };
  const filterEntries = Object.entries(input.appliedFilters);
  if (filterEntries.length === 0) {
    sheet.addRow(['(none)']);
  } else {
    filterEntries.forEach(([key, value]) => {
      sheet.addRow([key, value]);
    });
  }
  sheet.addRow([]);

  const totalsHeader = sheet.addRow(['Totals']);
  totalsHeader.font = { bold: true };
  const totals: [string, string][] = [
    ['Orders included', input.summary.order_count],
    ['Total Trip Fare', input.summary.total_trip_fare],
    ['Total Rider Share', input.summary.total_rider_share],
    ['Total Company Commission', input.summary.total_company_commission],
    ['Total Taxable Company Amount', input.summary.total_taxable_company_amount],
    ['Total GST', input.summary.total_gst],
    ['Total Operational Cost', input.summary.total_operational_cost],
    ['Total Company Profit', input.summary.total_company_profit],
  ];
  totals.forEach(([label, value], index) => {
    const row = sheet.addRow([label, index === 0 ? Number(value) : money(value)]);
    if (index > 0) {
      row.getCell(2).numFmt = MONEY_FORMAT;
    }
  });

  if (Number(input.summary.unconfigured_order_count) > 0) {
    sheet.addRow([]);
    const warning = sheet.addRow([
      'Orders with no applicable GST configuration',
      Number(input.summary.unconfigured_order_count),
    ]);
    warning.font = { bold: true };
    sheet.addRow([
      'These orders are counted in fare, rider and commission totals but contribute no GST or profit. Publish a GST configuration covering their freeze date.',
    ]);
  }

  if (input.truncated) {
    sheet.addRow([]);
    const warning = sheet.addRow([
      `WARNING: transactions truncated at ${input.exportMaxRows} rows. Narrow the filters for a complete export.`,
    ]);
    warning.font = { bold: true };
  }

  sheet.addRow([]);
  const periodHeader = sheet.addRow([`Breakdown by ${input.groupLabel}`]);
  periodHeader.font = { bold: true };
  const groupHeader = sheet.addRow([
    input.groupLabel === 'month' ? 'Month' : 'Date',
    'Orders',
    'Trip Fare',
    'Rider Share',
    'Company Commission',
    'Taxable Amount',
    'GST',
    'Operational Cost',
    'Company Profit',
  ]);
  groupHeader.font = { bold: true };
  input.groups.forEach((group) => {
    const row = sheet.addRow([
      group.period,
      Number(group.order_count),
      money(group.trip_fare),
      money(group.rider_share),
      money(group.company_commission),
      money(group.taxable_company_amount),
      money(group.gst_amount),
      money(group.operational_cost),
      money(group.company_profit),
    ]);
    for (let column = 3; column <= 9; column += 1) {
      row.getCell(column).numFmt = MONEY_FORMAT;
    }
  });

  const totalRow = sheet.addRow([
    'TOTAL',
    Number(input.summary.order_count),
    money(input.summary.total_trip_fare),
    money(input.summary.total_rider_share),
    money(input.summary.total_company_commission),
    money(input.summary.total_taxable_company_amount),
    money(input.summary.total_gst),
    money(input.summary.total_operational_cost),
    money(input.summary.total_company_profit),
  ]);
  totalRow.font = { bold: true };
  for (let column = 3; column <= 9; column += 1) {
    totalRow.getCell(column).numFmt = MONEY_FORMAT;
  }
}

function addLabelled(
  sheet: ReturnType<Workbook['addWorksheet']>,
  label: string,
  value: string,
): void {
  const row = sheet.addRow([label, value]);
  row.getCell(1).font = { bold: true };
}

const TRANSACTION_COLUMNS: {
  header: string;
  key: keyof GstDetailRow | 'blank';
  money?: boolean;
  numeric?: boolean;
}[] = [
  { header: 'Date', key: 'report_date' },
  { header: 'Order ID', key: 'order_id' },
  { header: 'Display ID', key: 'display_id' },
  { header: 'Customer', key: 'customer_name' },
  { header: 'Rider Phone', key: 'rider_phone' },
  { header: 'City', key: 'city_name' },
  { header: 'Vehicle Category', key: 'vehicle_category_name' },
  { header: 'Trip Fare', key: 'trip_fare', money: true },
  { header: 'Rider Share %', key: 'rider_percentage', numeric: true },
  { header: 'Rider Share Amount', key: 'rider_amount', money: true },
  {
    header: 'Company Commission %',
    key: 'company_commission_percentage',
    numeric: true,
  },
  {
    header: 'Company Commission Amount',
    key: 'company_commission_amount',
    money: true,
  },
  { header: 'GST Rate', key: 'gst_rate', numeric: true },
  { header: 'GST Calculation Basis', key: 'gst_basis' },
  { header: 'Taxable Company Amount', key: 'taxable_company_amount', money: true },
  { header: 'GST Amount', key: 'gst_amount', money: true },
  {
    header: 'Operational Cost %',
    key: 'operational_cost_percentage_of_commission',
    numeric: true,
  },
  { header: 'Operational Cost Amount', key: 'operational_cost_amount', money: true },
  { header: 'Company Profit', key: 'company_profit_amount', money: true },
  { header: 'Payment Status', key: 'payment_status' },
  { header: 'Order Status', key: 'order_status' },
  { header: 'GST Frozen At Source', key: 'tax_frozen' },
];

function buildTransactionsSheet(workbook: Workbook, input: WorkbookInput): void {
  const sheet = workbook.addWorksheet('Transactions');
  sheet.columns = TRANSACTION_COLUMNS.map((column) => ({
    width: Math.max(14, Math.min(30, column.header.length + 4)),
  }));

  const header = sheet.addRow(TRANSACTION_COLUMNS.map((column) => column.header));
  header.font = { bold: true };
  sheet.views = [{ state: 'frozen', ySplit: 1 }];

  input.detail.forEach((record) => {
    const values = TRANSACTION_COLUMNS.map((column) => {
      const raw = record[column.key as keyof GstDetailRow];
      if (raw == null) return null;
      if (column.money || column.numeric) {
        return Number(raw as string);
      }
      if (typeof raw === 'boolean') {
        return raw ? 'YES' : 'NO';
      }
      return String(raw);
    });
    const row = sheet.addRow(values);
    TRANSACTION_COLUMNS.forEach((column, index) => {
      if (column.money) {
        row.getCell(index + 1).numFmt = MONEY_FORMAT;
      }
    });
  });

  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: TRANSACTION_COLUMNS.length },
  };
}
